# Generated by Django 5.1.6 on 2025-03-02 22:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('initial_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SAL', 'Зарплата'), ('BON', 'Премия'), ('CPA', 'Выплата подрядчику'), ('PMA', 'Покупка материалов'), ('PEQ', 'Покупка оборудования'), ('REP', 'Представительские')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRE', 'Аванс (Prepayment)'), ('BON', 'Премия (Bonus)'), ('ANO', 'Иное (Another)')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('INC', 'Доход'), ('EXP', 'Расход'), ('TRA', 'Перевод')], max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accounts')),
            ],
        ),
    ]
