# Generated by Django 5.1.6 on 2025-03-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
