# Generated by Django 5.1.6 on 2025-03-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accounts_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
