# Generated by Django 5.1.6 on 2025-03-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_operations_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='odbiorca',
            field=models.CharField(default='Третье лицо', max_length=100),
        ),
    ]
